[project]
name = "warmup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyparsing>=3.3.1",
    "tabulate>=0.9.0",
]

[toolpyright]
venvPath='.'
venv=".venv"
exclude=['.venv']
